name: Build
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Check
        run: yarn test --coverage
      - uses: raulanatol/jest-coverage-comment-action@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
